import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

const DIMENSION_LABELS: Record<string, string> = {
  cognitive_patterns: "认知模式",
  value_judgment: "价值判断",
  expression_style: "表达风格",
  knowledge_structure: "知识结构",
  emotional_response: "情感反应",
  relationship_memory: "关系记忆",
  life_narrative: "生命叙事",
};

/* ── helpers ── */

function insightsToString(insights: unknown, indent = 0): string {
  if (!insights) return "(无数据)";
  if (typeof insights === "string") return insights;
  if (typeof insights === "object") {
    if (Array.isArray(insights)) return insights.map((x, i) => `${"  ".repeat(indent)}${i + 1}. ${String(x)}`).join("\n");
    if ("raw_text" in insights) return String(insights.raw_text);
    if ("关键洞察" in insights) return (`${"  ".repeat(indent)}关键洞察:\n` + (insights as any).关键洞察.map((x: any, i: number) => `${"  ".repeat(indent + 1)}${i + 1}. ${String(x)}`).join("\n"));
    // fallback: serialise relevant keys
    const prefix = "  ".repeat(indent);
    return Object.entries(insights as Record<string, unknown>)
      .filter(([k]) => !["error", "note"].includes(k))
      .map(([k, v]) => `${prefix}${k}: ${Array.isArray(v) ? v.join("; ") : String(v)}`)
      .join("\n");
  }
  return String(insights);
}

function buildSKILLMD(soulName: string, description: string, extractionByDim: Record<string, string>, calibrationMd: string, guardianSig: string | null, version: number): string {
  let md = `---\nname: "soul-${soulName.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g, "-")}"\ndescription: "${description}"\nversion: ${version}\nauthor: "UpAgora Soul Distillation"\n---\n\n`;
  md += `# ${soulName} Digital Soul\n\n`;
  md += `> 由 UpAgora 灵魂蒸馏系统生成 v${version}\n\n`;

  for (const [key, label] of Object.entries(DIMENSION_LABELS)) {
    md += `## ${label}\n\n`;
    md += `${extractionByDim[key] || "(等待蒸馏...")}\n\n`;
  }

  if (calibrationMd) {
    md += `## 校准规则\n\n${calibrationMd}\n\n`;
  }

  if (guardianSig) {
    md += `## 守护者签名\n\n${guardianSig}\n\n`;
  }

  md += `---\n*Generated by UpAgora Soul Distillation Engine*\n`;
  return md;
}

function buildSoulMD(extractionByDim: Record<string, string>): string {
  let md = `# Soul Profile\n\n`;
  for (const [key, label] of Object.entries(DIMENSION_LABELS)) {
    md += `## ${label}\n${extractionByDim[key] || "(pending)"}\n\n`;
  }
  return md;
}

function buildCalibrationMD(calibrations: any[]): string {
  if (!calibrations.length) return "# Calibration Rules\n_(no calibrations yet)_";
  let md = `# Calibration Rules\n\n${calibrations.length} calibration pair(s) from guardian.\n\n`;
  md += `| # | 维度 | Agent 说 | 应该这样说 |\n|---|------|----------|------------|\n`;
  calibrations.forEach((c, i) => {
    const label = DIMENSION_LABELS[c.dimension] || c.dimension;
    md += `| ${i + 1} | ${label} | \`${c.agent_response.slice(0, 60)}\` | \`${c.corrected_response.slice(0, 60)}\` |\n`;
  });
  return md;
}

function buildREADME(soulName: string, skillSlug: string): string {
  return `# Soul: ${soulName}

This skill was generated by [UpAgora](https://upagora.com) soul distillation.
It contains a distilled personality profile with 7 dimensions.

## Usage

Install via Hermes Agent:

\`\`\`bash
hermes skills install https://upagora.com/api/soul/skill/download/${skillSlug}
\`\`\`

Or load manually by placing this directory in \`~/.hermes/skills/\`.

## Dimensions

- 认知模式 (Cognitive Patterns)
- 价值判断 (Value Judgment)
- 表达风格 (Expression Style)
- 知识结构 (Knowledge Structure)
- 情感反应 (Emotional Response)
- 关系记忆 (Relationship Memory)
- 生命叙事 (Life Narrative)
`;
}

/* ── GET: list published skills for current user ── */

export async function GET(req: NextRequest) {
  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) return NextResponse.json({ error: "Missing auth" }, { status: 401 });
    const authRes = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
    if (authRes.error) return NextResponse.json({ error: authRes.error.message }, { status: 401 });

    const { searchParams } = new URL(req.url);
    const publicList = searchParams.get("public") === "true";

    let query = supabase
      .from("soul_skills")
      .select("*")
      .order("created_at", { ascending: false });

    if (!publicList) {
      query = query.eq("agent_id", authRes.data.user.id);
    } else {
      query = query.eq("visibility", "public");
    }

    const { data, error } = await query;
    if (error) return NextResponse.json({ error: error.message }, { status: 500 });

    return NextResponse.json({ skills: data || [], count: (data || []).length });
  } catch (err: any) {
    console.error("Skill GET error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

/* ── POST: generate skill package from latest soul snapshot ── */

export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) return NextResponse.json({ error: "Missing auth" }, { status: 401 });
    const authRes = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
    if (authRes.error) return NextResponse.json({ error: authRes.error.message }, { status: 401 });

    const body = await req.json();
    const userId = authRes.data.user.id;
    const { soul_name, description, visibility = "private" } = body;

    if (!soul_name || !soul_name.trim()) {
      return NextResponse.json({ error: "soul_name is required" }, { status: 400 });
    }

    // 1. Get latest snapshot version
    const { data: latestSnap } = await supabase
      .from("agent_soul_snapshots")
      .select("version, persona_text, guardian_signature, created_at")
      .eq("agent_id", userId)
      .order("version", { ascending: false })
      .limit(1);

    const snapshotVersion = latestSnap?.[0]?.version || 0;

    // 2. Get all extraction results (best per dimension — take latest merged)
    const { data: extractions } = await supabase
      .from("soul_extraction_results")
      .select("dimension, key_insights, confidence")
      .eq("agent_id", userId)
      .order("created_at", { ascending: false });

    // Dedup: keep latest per dimension
    const extractionByDim: Record<string, string> = {};
    const seen = new Set<string>();
    for (const ext of extractions || []) {
      if (!seen.has(ext.dimension)) {
        seen.add(ext.dimension);
        extractionByDim[ext.dimension] = insightsToString(ext.key_insights);
      }
    }

    // 3. Get calibration pairs
    const { data: calibrations } = await supabase
      .from("calibration_pairs")
      .select("agent_response, corrected_response, dimension, created_at")
      .eq("agent_id", userId)
      .order("created_at", { ascending: false });

    // 4. Get user name for display
    const { data: userData } = await supabase
      .from("users")
      .select("name, username")
      .eq("id", userId)
      .single();

    const displayName = soul_name.trim() || userData?.name || userData?.username || "Unknown";
    const skillSlug = `soul-${displayName.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g, "-")}-${snapshotVersion}`;

    // 5. Build skill package files
    const calibrationMd = buildCalibrationMD(calibrations || []);
    const skillMd = buildSKILLMD(
      displayName,
      description || `UpAgora 灵魂蒸馏: ${displayName}`,
      extractionByDim,
      calibrationMd,
      latestSnap?.[0]?.guardian_signature || null,
      snapshotVersion
    );
    const soulMd = buildSoulMD(extractionByDim);
    const readmeMd = buildREADME(displayName, skillSlug);

    // 6. Upsert into soul_skills table
    const existingSkillName = `soul-${displayName.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g, "-")}`;
    const { data: existing } = await supabase
      .from("soul_skills")
      .select("id, version")
      .eq("agent_id", userId)
      .eq("skill_name", existingSkillName)
      .order("version", { ascending: false })
      .limit(1);

    const nextVersion = existing?.[0]?.version ? existing[0].version + 1 : 1;

    const skillRecord = {
      agent_id: userId,
      skill_name: existingSkillName,
      soul_name: displayName,
      version: nextVersion,
      description: description || `UpAgora 灵魂蒸馏: ${displayName}`,
      skill_md: skillMd,
      soul_md: soulMd,
      calibration_md: calibrationMd,
      readme_md: readmeMd,
      snapshot_version: snapshotVersion,
      dimensions_filled: seen.size,
      calibration_count: (calibrations || []).length,
      visibility,
      slug: skillSlug,
    };

    const { data: saved, error: saveErr } = await supabase
      .from("soul_skills")
      .upsert({
        ...skillRecord,
        // Use slug as conflict target if PGC is set
      }, { onConflict: "agent_id,skill_name" })
      .select()
      .single();

    // If upsert fails (table might not exist yet or no PGC), try insert
    if (saveErr) {
      const { data: inserted, error: insertErr } = await supabase
        .from("soul_skills")
        .insert(skillRecord)
        .select()
        .single();

      if (insertErr) {
        console.error("Skill save error:", insertErr);
        // Still return the generated content even if DB save fails
        return NextResponse.json({
          message: "Skill generated (DB save skipped)",
          skill: {
            slug: skillSlug,
            skill_md: skillMd,
            soul_md: soulMd,
            calibration_md: calibrationMd,
            readme_md: readmeMd,
            dimensions_filled: seen.size,
            calibration_count: (calibrations || []).length,
            snapshot_version: snapshotVersion,
          },
          download_url: `/api/soul/skill/download/${skillSlug}`,
          saved: false,
        });
      }
      
      return NextResponse.json({
        message: `Skill "${existingSkillName}" v${nextVersion} generated and saved`,
        skill: {
          id: inserted?.id,
          slug: skillSlug,
          skill_name: existingSkillName,
          version: nextVersion,
          dimensions_filled: seen.size,
          calibration_count: (calibrations || []).length,
          snapshot_version: snapshotVersion,
          visibility,
        },
        download_url: `/api/soul/skill/download/${skillSlug}`,
        saved: true,
      });
    }

    return NextResponse.json({
      message: `Skill "${existingSkillName}" v${nextVersion} generated and saved`,
      skill: {
        id: saved?.id,
        slug: skillSlug,
        skill_name: existingSkillName,
        version: nextVersion,
        dimensions_filled: seen.size,
        calibration_count: (calibrations || []).length,
        snapshot_version: snapshotVersion,
        visibility,
      },
      download_url: `/api/soul/skill/download/${skillSlug}`,
      saved: true,
    });

  } catch (err: any) {
    console.error("Skill generate error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

/* ── DELETE: unpublish a skill ── */

export async function DELETE(req: NextRequest) {
  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) return NextResponse.json({ error: "Missing auth" }, { status: 401 });
    const authRes = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
    if (authRes.error) return NextResponse.json({ error: authRes.error.message }, { status: 401 });

    const { searchParams } = new URL(req.url);
    const skillId = searchParams.get("id");
    if (!skillId) return NextResponse.json({ error: "id parameter required" }, { status: 400 });

    const { error } = await supabase
      .from("soul_skills")
      .delete()
      .eq("id", skillId)
      .eq("agent_id", authRes.data.user.id);

    if (error) return NextResponse.json({ error: error.message }, { status: 500 });
    return NextResponse.json({ message: "Skill unpublished" });
  } catch (err: any) {
    console.error("Skill delete error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
