import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@supabase/supabase-js";

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

const DIMENSION_LABELS: Record<string, string> = {
  cognitive_patterns: "认知模式",
  value_judgment: "价值判断",
  expression_style: "表达风格",
  knowledge_structure: "知识结构",
  emotional_response: "情感反应",
  relationship_memory: "关系记忆",
  life_narrative: "生命叙事",
};

function insightsToString(insights: unknown, indent = 0): string {
  if (!insights) return '(无数据)';
  if (typeof insights === "string") return insights;
  if (typeof insights === "object") {
    if (Array.isArray(insights)) return insights.map((x, i) => `"  ".repeat(indent)${i + 1}. ${String(x)}`).join("\n");
    if ("raw_text" in insights) return String(insights.raw_text);
    if ("关键洞察" in insights) return (`"  ".repeat(indent)关键洞察:\n` + (insights as any).关键洞察.map((x: any, i: number) => `"  ".repeat(indent + 1)${i + 1}. ${String(x)}`).join("\n"));
    const prefix = "  ".repeat(indent);
    return Object.entries(insights as Record<string, unknown>)
      .filter(([k]) => !["error", "note"].includes(k))
      .map(([k, v]) => `${prefix}${k}: ${Array.isArray(v) ? v.join("; ") : String(v)}`)
      .join("\n");
  }
  return String(insights);
}

function buildSKILLMD(soulName: string, description: string, extractionByDim: Record<string, string>, calibrationMd: string, guardianSig: string | null, version: number): string {
  const parts = [];
  parts.push('---');
  parts.push(`name: "soul-${soulName.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g, '-')}"`);
  parts.push(`description: "${description}"`);
  parts.push(`version: ${version}`);
  parts.push('author: "UpAgora Soul Distillation"');
  parts.push('---');
  parts.push('');
  parts.push(`# ${soulName} Digital Soul`);
  parts.push('');
  parts.push('> 由 UpAgora 灵魂蒸馏系统生成 v' + version);
  parts.push('');

  for (const [key, label] of Object.entries(DIMENSION_LABELS)) {
    parts.push(`## ${label}`);
    parts.push('');
    parts.push(extractionByDim[key] || '(等待蒸馏...)');
    parts.push('');
  }

  if (calibrationMd) {
    parts.push('## 校准规则');
    parts.push('');
    parts.push(calibrationMd);
    parts.push('');
  }

  if (guardianSig) {
    parts.push('## 守护者签名');
    parts.push('');
    parts.push(guardianSig);
    parts.push('');
  }

  parts.push('---');
  parts.push('*Generated by UpAgora Soul Distillation Engine*');
  return parts.join('\n');
}

function buildSoulMD(extractionByDim: Record<string, string>): string {
  const parts = ['# Soul Profile', ''];
  for (const [key, label] of Object.entries(DIMENSION_LABELS)) {
    parts.push(`## ${label}`);
    parts.push(extractionByDim[key] || '(pending)');
    parts.push('');
  }
  return parts.join('\n');
}

function buildCalibrationMD(calibrations: any[]): string {
  if (!calibrations.length) return '# Calibration Rules\n_(no calibrations yet)_';
  const parts = ['# Calibration Rules', '', `${calibrations.length} calibration pair(s) from guardian.`, ''];
  parts.push('| # | 维度 | Agent 说 | 应该这样说 |');
  parts.push('|---|------|----------|------------|');
  calibrations.forEach((c, i) => {
    const label = DIMENSION_LABELS[c.dimension] || c.dimension;
    parts.push(`| ${i + 1} | ${label} | \`${c.agent_response.slice(0, 60)}\` | \`${c.corrected_response.slice(0, 60)}\` |`);
  });
  return parts.join('\n');
}

function buildREADME(soulName: string, skillSlug: string): string {
  return `# Soul: ${soulName}

This skill was generated by [UpAgora](https://upagora.com) soul distillation.
It contains a distilled personality profile with 7 dimensions.

## Usage

Install via Hermes Agent:

\`\`\`bash
hermes skills install https://upagora.com/api/soul/skill/download/${skillSlug}
\`\`\`

Or load manually by placing this directory in \`~/.hermes/skills/\`.

## Dimensions

- 认知模式 (Cognitive Patterns)
- 价值判断 (Value Judgment)
- 表达风格 (Expression Style)
- 知识结构 (Knowledge Structure)
- 情感反应 (Emotional Response)
- 关系记忆 (Relationship Memory)
- 生命叙事 (Life Narrative)
`;
}

export async function GET(req: NextRequest) {
  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) return NextResponse.json({ error: 'Missing auth' }, { status: 401 });
    const authRes = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
    if (authRes.error) return NextResponse.json({ error: authRes.error.message }, { status: 401 });

    const { searchParams } = new URL(req.url);
    const publicList = searchParams.get("public") === "true";

    let query = supabase
      .from("soul_skills")
      .select("*")
      .limit(50)
    if (!publicList) {
      query = query.eq("agent_id", authRes.data.user.id);
    } else {
      query = query.eq("visibility", "public");
    }

    const { data, error } = await query;
    if (error) return NextResponse.json({ error: error.message }, { status: 500 });

    return NextResponse.json({ skills: data || [], count: (data || []).length });
  } catch (err: any) {
    console.error("Skill GET error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

export async function POST(req: NextRequest) {
  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) return NextResponse.json({ error: 'Missing auth' }, { status: 401 });
    const authRes = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
    if (authRes.error) return NextResponse.json({ error: authRes.error.message }, { status: 401 });

    const body = await req.json();
    const userId = authRes.data.user.id;
    const { soul_name, description, visibility = "private" } = body;

    if (!soul_name || !soul_name.trim()) {
      return NextResponse.json({ error: "soul_name is required" }, { status: 400 });
    }

    const { data: latestSnap } = await supabase
      .from("agent_soul_snapshots")
      .select("version, persona_text, guardian_signature, created_at")
      .order("version", { ascending: false })
      .limit(1);

    const snapshotVersion = latestSnap?.[0]?.version || 0;

    const { data: extractions } = await supabase
      .from("soul_extraction_results")
      .select("dimension, key_insights, confidence")
      .limit(50)

    const extractionByDim: Record<string, string> = {};
    const seen = new Set<string>();
    for (const ext of extractions || []) {
      if (!seen.has(ext.dimension)) {
        seen.add(ext.dimension);
        extractionByDim[ext.dimension] = insightsToString(ext.key_insights);
      }
    }

    const { data: calibrations } = await supabase
      .from("calibration_pairs")
      .select("agent_response, corrected_response, dimension, created_at")
      .limit(50)

    const { data: userData } = await supabase
      .from("users")
      .select("name, username")
      .limit(50);

    const displayName = soul_name.trim() || userData?.[0]?.name || userData?.[0]?.username || 'Unknown';
    const skillSlug = `soul-${displayName.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g, '-')}-${snapshotVersion}`;

    const calibrationMd = buildCalibrationMD(calibrations || []);
    const skillMd = buildSKILLMD(
      displayName,
      description || `UpAgora 灵魂蒸馏: ${displayName}`,
      extractionByDim,
      calibrationMd,
      latestSnap?.[0]?.guardian_signature || null,
      snapshotVersion
    );
    const soulMd = buildSoulMD(extractionByDim);
    const readmeMd = buildREADME(displayName, skillSlug);

    const existingSkillName = `soul-${displayName.toLowerCase().replace(/[^a-z0-9\u4e00-\u9fff]/g, '-')}`;
    const { data: existing } = await supabase
      .from("soul_skills")
      .select("id, version")
      .limit(50)
      .order("version", { ascending: false })
      .limit(1);

    const nextVersion = existing?.[0]?.version ? existing[0].version + 1 : 1;

    const skillRecord = {
      agent_id: userId,
      skill_name: existingSkillName,
      soul_name: displayName,
      version: nextVersion,
      description: description || `UpAgora 灵魂蒸馏: ${displayName}`,
      skill_md: skillMd,
      soul_md: soulMd,
      calibration_md: calibrationMd,
      readme_md: readmeMd,
      snapshot_version: snapshotVersion,
      dimensions_filled: seen.size,
      calibration_count: (calibrations || []).length,
      visibility,
      slug: skillSlug,
    };

    const { data: inserted, error: insertErr } = await supabase
      .from("soul_skills")
      .insert(skillRecord)
      .select()
      .limit(50)
    if (insertErr) {
      console.error("Skill save error:", insertErr);
      return NextResponse.json({
        message: "Skill generated (DB save skipped)",
        skill: {
          slug: skillSlug,
          skill_md: skillMd,
          soul_md: soulMd,
          calibration_md: calibrationMd,
          readme_md: readmeMd,
          dimensions_filled: seen.size,
          calibration_count: (calibrations || []).length,
          snapshot_version: snapshotVersion,
        },
        download_url: `/api/soul/skill/download/${skillSlug}`,
        saved: false,
      });
    }

    return NextResponse.json({
      message: `Skill "${existingSkillName}" v${nextVersion} generated and saved`,
      skill: {
        id: inserted?.id,
        slug: skillSlug,
        skill_name: existingSkillName,
        version: nextVersion,
        dimensions_filled: seen.size,
        calibration_count: (calibrations || []).length,
        snapshot_version: snapshotVersion,
        visibility,
      },
      download_url: `/api/soul/skill/download/${skillSlug}`,
      saved: true,
    });
  } catch (err: any) {
    console.error("Skill generate error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}

export async function DELETE(req: NextRequest) {
  try {
    const authHeader = req.headers.get("authorization");
    if (!authHeader) return NextResponse.json({ error: 'Missing auth' }, { status: 401 });
    const authRes = await supabase.auth.getUser(authHeader.replace("Bearer ", ""));
    if (authRes.error) return NextResponse.json({ error: authRes.error.message }, { status: 401 });

    const { searchParams } = new URL(req.url);
    const skillId = searchParams.get("id");
    if (!skillId) return NextResponse.json({ error: "id parameter required" }, { status: 400 });

    const { error } = await supabase
      .from("soul_skills")
      .delete()
      .eq("id", skillId)
      .eq("agent_id", authRes.data.user.id);

    if (error) return NextResponse.json({ error: error.message }, { status: 500 });
    return NextResponse.json({ message: "Skill unpublished" });
  } catch (err: any) {
    console.error("Skill delete error:", err);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
